LANGUAGE_CONFIG = {
    "English": {"code": "eng_Latn", "filename": "english"},
    "Hindi": {"code": "hin_Deva", "filename": "hindi"},
    "Nepali": {"code": "npi_Deva", "filename": "nepali"},
    "Bengali": {"code": "ben_Beng", "filename": "bengali"},
    "Gujarati": {"code": "guj_Gujr", "filename": "gujarati"},
    "Marathi": {"code": "mar_Deva", "filename": "marathi"},
    "Punjabi": {"code": "pan_Guru", "filename": "punjabi"},
    "Tamil": {"code": "tam_Taml", "filename": "tamil"},
    "Telugu": {"code": "tel_Telu", "filename": "telugu"},
    "Urdu": {"code": "urd_Arab", "filename": "urdu"},
    "French": {"code": "fra_Latn", "filename": "french"},
    "German": {"code": "deu_Latn", "filename": "german"},
    "Spanish": {"code": "spa_Latn", "filename": "spanish"},
    "Italian": {"code": "ita_Latn", "filename": "italian"},
    "Portuguese": {"code": "por_Latn", "filename": "portuguese"},
    "Russian": {"code": "rus_Cyrl", "filename": "russian"},
    "Japanese": {"code": "jpn_Jpan", "filename": "japanese"},
    "Korean": {"code": "kor_Hang", "filename": "korean"},
    "Chinese (Simplified)": {"code": "zho_Hans", "filename": "chinese_simplified"},
    "Arabic": {"code": "arb_Arab", "filename": "arabic"},
}
